from fastapi import Depends, Header, HTTPException
from sqlmodel import Session, select

from app.db import get_session
from app.models import Org


def get_org(x_session_id: str = Header(..., description="Anonymous browser session UUID, generated by the frontend"),
            session: Session = Depends(get_session)) -> Org:
    org = session.exec(select(Org).where(Org.session_id == x_session_id)).first()
    if not org:
        org = Org(session_id=x_session_id)
        session.add(org)
        session.commit()
        session.refresh(org)
    return org


def get_or_404(session: Session, model, id_):
    obj = session.get(model, id_)
    if obj is None:
        raise HTTPException(404, f"{model.__name__} {id_} not found")
    return obj
